name: URL Status Code Checker
on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'Enter URLs separated by lines'
        required: true
jobs:
  check-status-codes:
    runs-on: ubuntu-latest
    steps:
      - name: Check status codes
        run: |
          urls=(${{ github.event.inputs.urls }})
          for url in "${urls[@]}"
          do
            status_code=$(curl -o /dev/null -s -w "%{http_code}\n" $url)
            echo "$url - $status_code"
          done
